CREATE DATABASE Compugraf
GO



CREATE TABLE [dbo].[PESSOA](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NOME] [varchar](400) NOT NULL,
	[SOBRENOME] [varchar](1000) NOT NULL,
	[NACIONALIDADE] [varchar](200) NOT NULL,
	[CEP] [varchar](100) NOT NULL,
	[ESTADO] [varchar](10) NOT NULL,
	[CIDADE] [varchar](100) NOT NULL,
	[LOGRADOURO] [varchar](1000) NOT NULL,
	[EMAIL] [varchar](200) NULL,
	[TELEFONE] [varchar](20) NULL,
 CONSTRAINT [PK_PESSOA] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
